server:
  port: 10953
spring:
  application:
    name: mm-art
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
    fetch-registry: false
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 30
